project:
  type: website

website:
  title: "Shivang Bhatt"
  navbar:
    background: "#0c2d6b"
    foreground: "#ffffff"
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/shivang-bhatt-data
      - icon: twitter-x
        href: https://x.com/swwangg
      - icon: envelope
        href: mailto:s1bhatt@ucsd.edu

format:
  html:
    theme:
      light: cosmo
    css: style.css
    toc: false
